name: 'Bicep Action'
description: 'Testing with Bicep Action'
author: 'Anthony Martin'
inputs:
  subscriptionId:
    required: true
    description: 'Subscription Id'
  resourceGroup:
    required: true
    description: 'Resource Group'
  templateFile:
    required: true
    description: 'Template File'
  parametersFile:
    required: true
    description: 'Parameters File'
  whatIf:
    required: false
    description: 'Run what-if'
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'