name: 'Bicep Action'
description: 'Runs various Bicep deployment scenarios'
author: 'Anthony Martin'
inputs:
  repo-token:
    description: "A GitHub token for API access. Defaults to {{ github.token }}."
    default: "${{ github.token }}"
    required: true
  config:
    description: "Path to the JSON configuration file"
    required: true
  action:
    description: "The action to perform"
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'