name: Test
on:
  pull_request:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    environment: 
      name: Test

    steps:
      - uses: actions/checkout@v3

      - name: AzCLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Live Test
        uses: ./
        with:
          subscriptionId: d08e1a72-8180-4ed3-8125-9dff7376b0bd
          resourceGroup: ant-test
          templateFile: test/scenarios/static-error/main.bicep
          parametersFile: test/scenarios/static-error/main.bicepparam
